version: '3'
services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: development
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
  server:
    container_name: server
    build:
      dockerfile: ./server/Dockerfile
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - ./server:/server
volumes:
  db-store: